config/routes.rb
Fumblr::Application.routes.draw do
  resources :fumbls

  root :to => 'fumbls#index'

end

app/models/fumbl.rb
class Fumbl < ActiveRecord::Base
  attr_accessible :body, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fumbls_controller.rb
class FumblsController < ApplicationController
  # GET /fumbls
  # GET /fumbls.json
  def index
    @fumbls = Fumbl.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fumbls }
    end
  end

  # GET /fumbls/1
  # GET /fumbls/1.json
  def show
    @fumbl = Fumbl.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fumbl }
    end
  end

  # GET /fumbls/new
  # GET /fumbls/new.json
  def new
    @fumbl = Fumbl.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fumbl }
    end
  end

  # GET /fumbls/1/edit
  def edit
    @fumbl = Fumbl.find(params[:id])
  end

  # POST /fumbls
  # POST /fumbls.json
  def create
    @fumbl = Fumbl.new(params[:fumbl])

    respond_to do |format|
      if @fumbl.save
        format.html { redirect_to @fumbl, notice: 'Fumbl was successfully created.' }
        format.json { render json: @fumbl, status: :created, location: @fumbl }
      else
        format.html { render action: "new" }
        format.json { render json: @fumbl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fumbls/1
  # PUT /fumbls/1.json
  def update
    @fumbl = Fumbl.find(params[:id])

    respond_to do |format|
      if @fumbl.update_attributes(params[:fumbl])
        format.html { redirect_to @fumbl, notice: 'Fumbl was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fumbl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fumbls/1
  # DELETE /fumbls/1.json
  def destroy
    @fumbl = Fumbl.find(params[:id])
    @fumbl.destroy

    respond_to do |format|
      format.html { redirect_to fumbls_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fumbls_helper.rb
module FumblsHelper
end

app/views/fumbls/_form.html.erb
<%= form_for(@fumbl) do |f| %>
  <% if @fumbl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fumbl.errors.count, "error") %> prohibited this fumbl from being saved:</h2>

      <ul>
      <% @fumbl.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fumbls/edit.html.erb
<h1>Editing fumbl</h1>

<%= render 'form' %>

<%= link_to 'Show', @fumbl %> |
<%= link_to 'Back', fumbls_path %>

app/views/fumbls/index.html.erb
<h1>Listing fumbls</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fumbls.each do |fumbl| %>
  <tr>
    <td><%= link_to fumbl.title, fumbl %></td>
    <td>[<%= link_to 'Edit', edit_fumbl_path(fumbl) %></td>
    <td><%= link_to 'Destroy', fumbl, method: :delete, data: { confirm: 'Are you sure?' } %>]</td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fumbl', new_fumbl_path %>

app/views/fumbls/new.html.erb
<h1>New fumbl</h1>

<%= render 'form' %>

<%= link_to 'Back', fumbls_path %>

app/views/fumbls/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @fumbl.title %>
</h1>

<div class='body'>
  <%= @fumbl.body %>
</div>


<%= link_to 'Edit', edit_fumbl_path(@fumbl) %> |
<%= link_to 'Back', fumbls_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>